<?php
/**
 * TvstationsGetApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API v3
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * TvstationsGetApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TvstationsGetApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v3TvstationsGet
     *
     * Retrieves all available TV stations.
     *
     * @param  string[] $fields Selects the fields that will be transmitted in the response. The field names are comma-separated, case-insensitive and will be trimmed.    The field \&quot;id\&quot; is always transmitted.    _The allowed field values:_    homepageurl,    id,    isrecordable,    largelogourl,    livestream,    name,    smalllogourl (optional, default to ["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"])
     * @param  bool $has_live_stream Select only TV stations that provide / provide not a live stream. (optional)
     * @param  bool $is_recordable Select only TV station that are / ar not recordable. (optional)
     * @param  \Swagger\Client\Model\SortDescription[] $sort Sets the sort properties. The values are comma-separated. To sort ascending add a \&quot;+\&quot; before the sort property, to sort descending add a \&quot;-\&quot; before the sort property.    When omitted, a default sorting is used.    Example: sort&#x3D;+prop1,-prop2    Sorts first by prop1 ascending then by prop2 descending.    Allowed sort properties:    name    priority    Default sorting:    +priority (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ResponseTvStation[]
     */
    public function v3TvstationsGet($fields = '["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"]', $has_live_stream = null, $is_recordable = null, $sort = null)
    {
        list($response) = $this->v3TvstationsGetWithHttpInfo($fields, $has_live_stream, $is_recordable, $sort);
        return $response;
    }

    /**
     * Operation v3TvstationsGetWithHttpInfo
     *
     * Retrieves all available TV stations.
     *
     * @param  string[] $fields Selects the fields that will be transmitted in the response. The field names are comma-separated, case-insensitive and will be trimmed.    The field \&quot;id\&quot; is always transmitted.    _The allowed field values:_    homepageurl,    id,    isrecordable,    largelogourl,    livestream,    name,    smalllogourl (optional, default to ["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"])
     * @param  bool $has_live_stream Select only TV stations that provide / provide not a live stream. (optional)
     * @param  bool $is_recordable Select only TV station that are / ar not recordable. (optional)
     * @param  \Swagger\Client\Model\SortDescription[] $sort Sets the sort properties. The values are comma-separated. To sort ascending add a \&quot;+\&quot; before the sort property, to sort descending add a \&quot;-\&quot; before the sort property.    When omitted, a default sorting is used.    Example: sort&#x3D;+prop1,-prop2    Sorts first by prop1 ascending then by prop2 descending.    Allowed sort properties:    name    priority    Default sorting:    +priority (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ResponseTvStation[], HTTP status code, HTTP response headers (array of strings)
     */
    public function v3TvstationsGetWithHttpInfo($fields = '["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"]', $has_live_stream = null, $is_recordable = null, $sort = null)
    {
        $returnType = '\Swagger\Client\Model\ResponseTvStation[]';
        $request = $this->v3TvstationsGetRequest($fields, $has_live_stream, $is_recordable, $sort);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ResponseTvStation[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v3TvstationsGetAsync
     *
     * Retrieves all available TV stations.
     *
     * @param  string[] $fields Selects the fields that will be transmitted in the response. The field names are comma-separated, case-insensitive and will be trimmed.    The field \&quot;id\&quot; is always transmitted.    _The allowed field values:_    homepageurl,    id,    isrecordable,    largelogourl,    livestream,    name,    smalllogourl (optional, default to ["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"])
     * @param  bool $has_live_stream Select only TV stations that provide / provide not a live stream. (optional)
     * @param  bool $is_recordable Select only TV station that are / ar not recordable. (optional)
     * @param  \Swagger\Client\Model\SortDescription[] $sort Sets the sort properties. The values are comma-separated. To sort ascending add a \&quot;+\&quot; before the sort property, to sort descending add a \&quot;-\&quot; before the sort property.    When omitted, a default sorting is used.    Example: sort&#x3D;+prop1,-prop2    Sorts first by prop1 ascending then by prop2 descending.    Allowed sort properties:    name    priority    Default sorting:    +priority (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3TvstationsGetAsync($fields = '["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"]', $has_live_stream = null, $is_recordable = null, $sort = null)
    {
        return $this->v3TvstationsGetAsyncWithHttpInfo($fields, $has_live_stream, $is_recordable, $sort)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v3TvstationsGetAsyncWithHttpInfo
     *
     * Retrieves all available TV stations.
     *
     * @param  string[] $fields Selects the fields that will be transmitted in the response. The field names are comma-separated, case-insensitive and will be trimmed.    The field \&quot;id\&quot; is always transmitted.    _The allowed field values:_    homepageurl,    id,    isrecordable,    largelogourl,    livestream,    name,    smalllogourl (optional, default to ["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"])
     * @param  bool $has_live_stream Select only TV stations that provide / provide not a live stream. (optional)
     * @param  bool $is_recordable Select only TV station that are / ar not recordable. (optional)
     * @param  \Swagger\Client\Model\SortDescription[] $sort Sets the sort properties. The values are comma-separated. To sort ascending add a \&quot;+\&quot; before the sort property, to sort descending add a \&quot;-\&quot; before the sort property.    When omitted, a default sorting is used.    Example: sort&#x3D;+prop1,-prop2    Sorts first by prop1 ascending then by prop2 descending.    Allowed sort properties:    name    priority    Default sorting:    +priority (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3TvstationsGetAsyncWithHttpInfo($fields = '["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"]', $has_live_stream = null, $is_recordable = null, $sort = null)
    {
        $returnType = '\Swagger\Client\Model\ResponseTvStation[]';
        $request = $this->v3TvstationsGetRequest($fields, $has_live_stream, $is_recordable, $sort);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v3TvstationsGet'
     *
     * @param  string[] $fields Selects the fields that will be transmitted in the response. The field names are comma-separated, case-insensitive and will be trimmed.    The field \&quot;id\&quot; is always transmitted.    _The allowed field values:_    homepageurl,    id,    isrecordable,    largelogourl,    livestream,    name,    smalllogourl (optional, default to ["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"])
     * @param  bool $has_live_stream Select only TV stations that provide / provide not a live stream. (optional)
     * @param  bool $is_recordable Select only TV station that are / ar not recordable. (optional)
     * @param  \Swagger\Client\Model\SortDescription[] $sort Sets the sort properties. The values are comma-separated. To sort ascending add a \&quot;+\&quot; before the sort property, to sort descending add a \&quot;-\&quot; before the sort property.    When omitted, a default sorting is used.    Example: sort&#x3D;+prop1,-prop2    Sorts first by prop1 ascending then by prop2 descending.    Allowed sort properties:    name    priority    Default sorting:    +priority (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v3TvstationsGetRequest($fields = '["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"]', $has_live_stream = null, $is_recordable = null, $sort = null)
    {

        $resourcePath = '/v3/tvstations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($fields)) {
            $fields = ObjectSerializer::serializeCollection($fields, 'multi', true);
        }
        if ($fields !== null) {
            $queryParams['fields'] = ObjectSerializer::toQueryValue($fields);
        }
        // query params
        if ($has_live_stream !== null) {
            $queryParams['hasLiveStream'] = ObjectSerializer::toQueryValue($has_live_stream);
        }
        // query params
        if ($is_recordable !== null) {
            $queryParams['isRecordable'] = ObjectSerializer::toQueryValue($is_recordable);
        }
        // query params
        if (is_array($sort)) {
            $sort = ObjectSerializer::serializeCollection($sort, 'multi', true);
        }
        if ($sort !== null) {
            $queryParams['sort'] = ObjectSerializer::toQueryValue($sort);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'application/x.cf-json-base64']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'application/x.cf-json-base64'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v3TvstationsTvstationIdGet
     *
     * Retrieves a single TV station with the given identifier.
     *
     * @param  int $tvstation_id The identifier of the TV station. (required)
     * @param  string[] $fields Selects the fields that will be transmitted in the response. The field names are comma-separated, case-insensitive and will be trimmed.    The field \&quot;id\&quot; is always transmitted.    _The allowed field values:_    homepageurl,    id,    isrecordable,    largelogourl,    livestream,    name,    smalllogourl (optional, default to ["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"])
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ResponseTvStation
     */
    public function v3TvstationsTvstationIdGet($tvstation_id, $fields = '["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"]')
    {
        list($response) = $this->v3TvstationsTvstationIdGetWithHttpInfo($tvstation_id, $fields);
        return $response;
    }

    /**
     * Operation v3TvstationsTvstationIdGetWithHttpInfo
     *
     * Retrieves a single TV station with the given identifier.
     *
     * @param  int $tvstation_id The identifier of the TV station. (required)
     * @param  string[] $fields Selects the fields that will be transmitted in the response. The field names are comma-separated, case-insensitive and will be trimmed.    The field \&quot;id\&quot; is always transmitted.    _The allowed field values:_    homepageurl,    id,    isrecordable,    largelogourl,    livestream,    name,    smalllogourl (optional, default to ["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"])
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ResponseTvStation, HTTP status code, HTTP response headers (array of strings)
     */
    public function v3TvstationsTvstationIdGetWithHttpInfo($tvstation_id, $fields = '["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"]')
    {
        $returnType = '\Swagger\Client\Model\ResponseTvStation';
        $request = $this->v3TvstationsTvstationIdGetRequest($tvstation_id, $fields);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ResponseTvStation',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v3TvstationsTvstationIdGetAsync
     *
     * Retrieves a single TV station with the given identifier.
     *
     * @param  int $tvstation_id The identifier of the TV station. (required)
     * @param  string[] $fields Selects the fields that will be transmitted in the response. The field names are comma-separated, case-insensitive and will be trimmed.    The field \&quot;id\&quot; is always transmitted.    _The allowed field values:_    homepageurl,    id,    isrecordable,    largelogourl,    livestream,    name,    smalllogourl (optional, default to ["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"])
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3TvstationsTvstationIdGetAsync($tvstation_id, $fields = '["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"]')
    {
        return $this->v3TvstationsTvstationIdGetAsyncWithHttpInfo($tvstation_id, $fields)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v3TvstationsTvstationIdGetAsyncWithHttpInfo
     *
     * Retrieves a single TV station with the given identifier.
     *
     * @param  int $tvstation_id The identifier of the TV station. (required)
     * @param  string[] $fields Selects the fields that will be transmitted in the response. The field names are comma-separated, case-insensitive and will be trimmed.    The field \&quot;id\&quot; is always transmitted.    _The allowed field values:_    homepageurl,    id,    isrecordable,    largelogourl,    livestream,    name,    smalllogourl (optional, default to ["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"])
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3TvstationsTvstationIdGetAsyncWithHttpInfo($tvstation_id, $fields = '["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"]')
    {
        $returnType = '\Swagger\Client\Model\ResponseTvStation';
        $request = $this->v3TvstationsTvstationIdGetRequest($tvstation_id, $fields);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v3TvstationsTvstationIdGet'
     *
     * @param  int $tvstation_id The identifier of the TV station. (required)
     * @param  string[] $fields Selects the fields that will be transmitted in the response. The field names are comma-separated, case-insensitive and will be trimmed.    The field \&quot;id\&quot; is always transmitted.    _The allowed field values:_    homepageurl,    id,    isrecordable,    largelogourl,    livestream,    name,    smalllogourl (optional, default to ["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"])
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v3TvstationsTvstationIdGetRequest($tvstation_id, $fields = '["homepageurl, id, isrecordable, largelogourl, livestream, name, smalllogourl"]')
    {
        // verify the required parameter 'tvstation_id' is set
        if ($tvstation_id === null || (is_array($tvstation_id) && count($tvstation_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tvstation_id when calling v3TvstationsTvstationIdGet'
            );
        }

        $resourcePath = '/v3/tvstations/{tvstationId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($fields)) {
            $fields = ObjectSerializer::serializeCollection($fields, 'multi', true);
        }
        if ($fields !== null) {
            $queryParams['fields'] = ObjectSerializer::toQueryValue($fields);
        }

        // path params
        if ($tvstation_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tvstationId' . '}',
                ObjectSerializer::toPathValue($tvstation_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'application/x.cf-json-base64']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'application/x.cf-json-base64'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
