<?php
/**
 * UserGetApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API v3
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * UserGetApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserGetApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v3UserAccesscodeVerificationGet
     *
     * Validates the AccessCode
     *
     * @param  string $access_code access_code (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v3UserAccesscodeVerificationGet($access_code = null)
    {
        $this->v3UserAccesscodeVerificationGetWithHttpInfo($access_code);
    }

    /**
     * Operation v3UserAccesscodeVerificationGetWithHttpInfo
     *
     * Validates the AccessCode
     *
     * @param  string $access_code (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v3UserAccesscodeVerificationGetWithHttpInfo($access_code = null)
    {
        $returnType = '';
        $request = $this->v3UserAccesscodeVerificationGetRequest($access_code);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation v3UserAccesscodeVerificationGetAsync
     *
     * Validates the AccessCode
     *
     * @param  string $access_code (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3UserAccesscodeVerificationGetAsync($access_code = null)
    {
        return $this->v3UserAccesscodeVerificationGetAsyncWithHttpInfo($access_code)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v3UserAccesscodeVerificationGetAsyncWithHttpInfo
     *
     * Validates the AccessCode
     *
     * @param  string $access_code (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3UserAccesscodeVerificationGetAsyncWithHttpInfo($access_code = null)
    {
        $returnType = '';
        $request = $this->v3UserAccesscodeVerificationGetRequest($access_code);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v3UserAccesscodeVerificationGet'
     *
     * @param  string $access_code (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v3UserAccesscodeVerificationGetRequest($access_code = null)
    {

        $resourcePath = '/v3/user/accesscode/verification';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($access_code !== null) {
            $queryParams['accessCode'] = ObjectSerializer::toQueryValue($access_code);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v3UserGet
     *
     * Endpoint for getting the data of the requesting user.
     *
     * @param  string[] $fields Selects the fields that will be transmitted in the response. The field names are comma-separated, case-insensitive and will be trimmed.    The field \&quot;id\&quot; is always transmitted.    _The allowed field values:_    catchall.haspermission,    contract.hasxlpackage,    contract.hasxxlpackage,    contract.iscancelled,    contract.islocked,    contract.isrunning,    contract.packagename,    erotic.isenabled,    fullname,    guard.isenabled,    id,    livestreaming.isenabled,    playlists.allowed,    recordbuffer.followuptime,    recordbuffer.leadtime,    recordformat.id,    recordformat.name,    retentiontime.daysdivx,    retentiontime.daysh264hd,    retentiontime.daysh264mobile,    retentiontime.daysh264sd,    retentiontime.hasextendedretentiontimepermission (optional, default to ["catchall.haspermission, contract.hasxlpackage, contract.hasxxlpackage, contract.iscancelled, contract.islocked, contract.isrunning, contract.packagename, erotic.isenabled, fullname, guard.isenabled, id, livestreaming.isenabled, playlists.allowed, recordbuffer.followuptime, recordbuffer.leadtime, recordformat.id, recordformat.name, retentiontime.daysdivx, retentiontime.daysh264hd, retentiontime.daysh264mobile, retentiontime.daysh264sd, retentiontime.hasextendedretentiontimepermission"])
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ResponseUser
     */
    public function v3UserGet($fields = '["catchall.haspermission, contract.hasxlpackage, contract.hasxxlpackage, contract.iscancelled, contract.islocked, contract.isrunning, contract.packagename, erotic.isenabled, fullname, guard.isenabled, id, livestreaming.isenabled, playlists.allowed, recordbuffer.followuptime, recordbuffer.leadtime, recordformat.id, recordformat.name, retentiontime.daysdivx, retentiontime.daysh264hd, retentiontime.daysh264mobile, retentiontime.daysh264sd, retentiontime.hasextendedretentiontimepermission"]')
    {
        list($response) = $this->v3UserGetWithHttpInfo($fields);
        return $response;
    }

    /**
     * Operation v3UserGetWithHttpInfo
     *
     * Endpoint for getting the data of the requesting user.
     *
     * @param  string[] $fields Selects the fields that will be transmitted in the response. The field names are comma-separated, case-insensitive and will be trimmed.    The field \&quot;id\&quot; is always transmitted.    _The allowed field values:_    catchall.haspermission,    contract.hasxlpackage,    contract.hasxxlpackage,    contract.iscancelled,    contract.islocked,    contract.isrunning,    contract.packagename,    erotic.isenabled,    fullname,    guard.isenabled,    id,    livestreaming.isenabled,    playlists.allowed,    recordbuffer.followuptime,    recordbuffer.leadtime,    recordformat.id,    recordformat.name,    retentiontime.daysdivx,    retentiontime.daysh264hd,    retentiontime.daysh264mobile,    retentiontime.daysh264sd,    retentiontime.hasextendedretentiontimepermission (optional, default to ["catchall.haspermission, contract.hasxlpackage, contract.hasxxlpackage, contract.iscancelled, contract.islocked, contract.isrunning, contract.packagename, erotic.isenabled, fullname, guard.isenabled, id, livestreaming.isenabled, playlists.allowed, recordbuffer.followuptime, recordbuffer.leadtime, recordformat.id, recordformat.name, retentiontime.daysdivx, retentiontime.daysh264hd, retentiontime.daysh264mobile, retentiontime.daysh264sd, retentiontime.hasextendedretentiontimepermission"])
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ResponseUser, HTTP status code, HTTP response headers (array of strings)
     */
    public function v3UserGetWithHttpInfo($fields = '["catchall.haspermission, contract.hasxlpackage, contract.hasxxlpackage, contract.iscancelled, contract.islocked, contract.isrunning, contract.packagename, erotic.isenabled, fullname, guard.isenabled, id, livestreaming.isenabled, playlists.allowed, recordbuffer.followuptime, recordbuffer.leadtime, recordformat.id, recordformat.name, retentiontime.daysdivx, retentiontime.daysh264hd, retentiontime.daysh264mobile, retentiontime.daysh264sd, retentiontime.hasextendedretentiontimepermission"]')
    {
        $returnType = '\Swagger\Client\Model\ResponseUser';
        $request = $this->v3UserGetRequest($fields);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ResponseUser',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v3UserGetAsync
     *
     * Endpoint for getting the data of the requesting user.
     *
     * @param  string[] $fields Selects the fields that will be transmitted in the response. The field names are comma-separated, case-insensitive and will be trimmed.    The field \&quot;id\&quot; is always transmitted.    _The allowed field values:_    catchall.haspermission,    contract.hasxlpackage,    contract.hasxxlpackage,    contract.iscancelled,    contract.islocked,    contract.isrunning,    contract.packagename,    erotic.isenabled,    fullname,    guard.isenabled,    id,    livestreaming.isenabled,    playlists.allowed,    recordbuffer.followuptime,    recordbuffer.leadtime,    recordformat.id,    recordformat.name,    retentiontime.daysdivx,    retentiontime.daysh264hd,    retentiontime.daysh264mobile,    retentiontime.daysh264sd,    retentiontime.hasextendedretentiontimepermission (optional, default to ["catchall.haspermission, contract.hasxlpackage, contract.hasxxlpackage, contract.iscancelled, contract.islocked, contract.isrunning, contract.packagename, erotic.isenabled, fullname, guard.isenabled, id, livestreaming.isenabled, playlists.allowed, recordbuffer.followuptime, recordbuffer.leadtime, recordformat.id, recordformat.name, retentiontime.daysdivx, retentiontime.daysh264hd, retentiontime.daysh264mobile, retentiontime.daysh264sd, retentiontime.hasextendedretentiontimepermission"])
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3UserGetAsync($fields = '["catchall.haspermission, contract.hasxlpackage, contract.hasxxlpackage, contract.iscancelled, contract.islocked, contract.isrunning, contract.packagename, erotic.isenabled, fullname, guard.isenabled, id, livestreaming.isenabled, playlists.allowed, recordbuffer.followuptime, recordbuffer.leadtime, recordformat.id, recordformat.name, retentiontime.daysdivx, retentiontime.daysh264hd, retentiontime.daysh264mobile, retentiontime.daysh264sd, retentiontime.hasextendedretentiontimepermission"]')
    {
        return $this->v3UserGetAsyncWithHttpInfo($fields)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v3UserGetAsyncWithHttpInfo
     *
     * Endpoint for getting the data of the requesting user.
     *
     * @param  string[] $fields Selects the fields that will be transmitted in the response. The field names are comma-separated, case-insensitive and will be trimmed.    The field \&quot;id\&quot; is always transmitted.    _The allowed field values:_    catchall.haspermission,    contract.hasxlpackage,    contract.hasxxlpackage,    contract.iscancelled,    contract.islocked,    contract.isrunning,    contract.packagename,    erotic.isenabled,    fullname,    guard.isenabled,    id,    livestreaming.isenabled,    playlists.allowed,    recordbuffer.followuptime,    recordbuffer.leadtime,    recordformat.id,    recordformat.name,    retentiontime.daysdivx,    retentiontime.daysh264hd,    retentiontime.daysh264mobile,    retentiontime.daysh264sd,    retentiontime.hasextendedretentiontimepermission (optional, default to ["catchall.haspermission, contract.hasxlpackage, contract.hasxxlpackage, contract.iscancelled, contract.islocked, contract.isrunning, contract.packagename, erotic.isenabled, fullname, guard.isenabled, id, livestreaming.isenabled, playlists.allowed, recordbuffer.followuptime, recordbuffer.leadtime, recordformat.id, recordformat.name, retentiontime.daysdivx, retentiontime.daysh264hd, retentiontime.daysh264mobile, retentiontime.daysh264sd, retentiontime.hasextendedretentiontimepermission"])
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3UserGetAsyncWithHttpInfo($fields = '["catchall.haspermission, contract.hasxlpackage, contract.hasxxlpackage, contract.iscancelled, contract.islocked, contract.isrunning, contract.packagename, erotic.isenabled, fullname, guard.isenabled, id, livestreaming.isenabled, playlists.allowed, recordbuffer.followuptime, recordbuffer.leadtime, recordformat.id, recordformat.name, retentiontime.daysdivx, retentiontime.daysh264hd, retentiontime.daysh264mobile, retentiontime.daysh264sd, retentiontime.hasextendedretentiontimepermission"]')
    {
        $returnType = '\Swagger\Client\Model\ResponseUser';
        $request = $this->v3UserGetRequest($fields);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v3UserGet'
     *
     * @param  string[] $fields Selects the fields that will be transmitted in the response. The field names are comma-separated, case-insensitive and will be trimmed.    The field \&quot;id\&quot; is always transmitted.    _The allowed field values:_    catchall.haspermission,    contract.hasxlpackage,    contract.hasxxlpackage,    contract.iscancelled,    contract.islocked,    contract.isrunning,    contract.packagename,    erotic.isenabled,    fullname,    guard.isenabled,    id,    livestreaming.isenabled,    playlists.allowed,    recordbuffer.followuptime,    recordbuffer.leadtime,    recordformat.id,    recordformat.name,    retentiontime.daysdivx,    retentiontime.daysh264hd,    retentiontime.daysh264mobile,    retentiontime.daysh264sd,    retentiontime.hasextendedretentiontimepermission (optional, default to ["catchall.haspermission, contract.hasxlpackage, contract.hasxxlpackage, contract.iscancelled, contract.islocked, contract.isrunning, contract.packagename, erotic.isenabled, fullname, guard.isenabled, id, livestreaming.isenabled, playlists.allowed, recordbuffer.followuptime, recordbuffer.leadtime, recordformat.id, recordformat.name, retentiontime.daysdivx, retentiontime.daysh264hd, retentiontime.daysh264mobile, retentiontime.daysh264sd, retentiontime.hasextendedretentiontimepermission"])
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v3UserGetRequest($fields = '["catchall.haspermission, contract.hasxlpackage, contract.hasxxlpackage, contract.iscancelled, contract.islocked, contract.isrunning, contract.packagename, erotic.isenabled, fullname, guard.isenabled, id, livestreaming.isenabled, playlists.allowed, recordbuffer.followuptime, recordbuffer.leadtime, recordformat.id, recordformat.name, retentiontime.daysdivx, retentiontime.daysh264hd, retentiontime.daysh264mobile, retentiontime.daysh264sd, retentiontime.hasextendedretentiontimepermission"]')
    {

        $resourcePath = '/v3/user';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($fields)) {
            $fields = ObjectSerializer::serializeCollection($fields, 'multi', true);
        }
        if ($fields !== null) {
            $queryParams['fields'] = ObjectSerializer::toQueryValue($fields);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'application/x.cf-json-base64']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'application/x.cf-json-base64'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
