<?php
/**
 * ResponseTvStationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API v3
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ResponseTvStationTest Class Doc Comment
 *
 * @category    Class
 * @description ResponseTvStation
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseTvStationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResponseTvStation"
     */
    public function testResponseTvStation()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "small_logo_url"
     */
    public function testPropertySmallLogoUrl()
    {
    }

    /**
     * Test attribute "large_logo_url"
     */
    public function testPropertyLargeLogoUrl()
    {
    }

    /**
     * Test attribute "homepage_url"
     */
    public function testPropertyHomepageUrl()
    {
    }

    /**
     * Test attribute "is_recordable"
     */
    public function testPropertyIsRecordable()
    {
    }

    /**
     * Test attribute "live_stream"
     */
    public function testPropertyLiveStream()
    {
    }
}
