<?php
/**
 * ChannelsPostApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API v3
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ChannelsPostApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ChannelsPostApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v3ChannelsCatchallPost
     *
     * Creates the catch all channels for the requested TV stations or for all TV stations..
     *
     */
    public function testV3ChannelsCatchallPost()
    {
    }

    /**
     * Test case for v3ChannelsFulltextsearchPost
     *
     * Creates a full text search channel..
     *
     */
    public function testV3ChannelsFulltextsearchPost()
    {
    }

    /**
     * Test case for v3ChannelsStarPost
     *
     * Creates a star channel..
     *
     */
    public function testV3ChannelsStarPost()
    {
    }

    /**
     * Test case for v3ChannelsTelecastidsPost
     *
     * Creates a channel by various telecast ids..
     *
     */
    public function testV3ChannelsTelecastidsPost()
    {
    }

    /**
     * Test case for v3ChannelsTitlePost
     *
     * Creates a title channel..
     *
     */
    public function testV3ChannelsTitlePost()
    {
    }

    /**
     * Test case for v3ChannelsTvstationPost
     *
     * Creates a TV station channel..
     *
     */
    public function testV3ChannelsTvstationPost()
    {
    }
}
