<?php
/**
 * TelecastsGetApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API v3
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * TelecastsGetApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TelecastsGetApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v3TelecastsGet
     *
     * Retrieves the telecasts that match the filter condition..
     *
     */
    public function testV3TelecastsGet()
    {
    }

    /**
     * Test case for v3TelecastsSuggestionsGet
     *
     * Provides suggestions for the telecast search text..
     *
     */
    public function testV3TelecastsSuggestionsGet()
    {
    }

    /**
     * Test case for v3TelecastsTelecastIdFollowersGet
     *
     * Retrieves the following telecasts for a telecast..
     *
     */
    public function testV3TelecastsTelecastIdFollowersGet()
    {
    }

    /**
     * Test case for v3TelecastsTelecastIdGet
     *
     * Retrieves a single telecast with the given identifier..
     *
     */
    public function testV3TelecastsTelecastIdGet()
    {
    }

    /**
     * Test case for v3TelecastsUserrecommendationsTvCategoryIdGet
     *
     * Retrieves the user recommendations for a TV category..
     *
     */
    public function testV3TelecastsUserrecommendationsTvCategoryIdGet()
    {
    }
}
